lilydjwg/nvchecker

tests/helper.py
tests/test_cmd.py
tests/test_cpan.py
tests/test_gems.py
tests/test_hackage.py
tests/test_pypi.py

The cmd test currently fails and I don't have an idea :/

Add more tests

---

setup.py

It will be located under site-packages/ and easy to conflict with other packages.

Don't install tests directory

---

nvchecker/source/github.py

Before:
```
[E 01-09 11:26:03.736 core:132] unexpected error happened with dnscrypt-proxy
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/nvchecker/core.py", line 128, in future_done
version = fu.result()
File "/usr/lib/python3.6/site-packages/nvchecker/get_version.py", line 43, in get_version
version = await func(name, conf)
File "/usr/lib/python3.6/site-packages/nvchecker/source/github.py", line 43, in get_version
version = data[-1]
IndexError: list index out of range
```
After:
```
[E 01-09 11:32:35.308 github:50] dnscrypt-proxy: No tag found in upstream repository.
```

Handle exception for no-tag situation

---

.travis.yml
setup.py
tests/test_anitya.py

I'm just too lazy to test it locally before creating a pull request :P

Also test tornado<5

---

nvchecker/source/aur.py
tests/test_aur.py

https://github.com/archlinuxcn/repo/issues/872
这样？

added use_last_modified for aur

---

nvchecker/source/aiohttp_httpclient.py
nvchecker/source/simple_json.py
nvchecker/source/tornado_httpclient.py

After the changes the `aiohttp` backend works flawlessly here.

Aiohttp fixes

---

.travis.yml
nvchecker/source/pypi.py

Fix checking for such an nvchecker.ini:
```
[logcat-color]
pypi =
```
Also cleanup unused stuffs.

pypi: fix valueless items

---

README.rst
nvchecker/source/github.py
tests/test_github.py

added path to github source

---

README.rst

Fix copy-paste mistake

---

nvchecker/source/pacman.py
tests/test_archpkg.py
tests/test_pacman.py

Both are quite straightforward. See commit meesages for details.

Pacman fixes and updates

---

nvchecker/lib/nicelogger.py
nvchecker/tools.py

Also refactored nicelogger to reuse the logic there.

Make nvcmp output colorful

---

nvchecker/core.py
nvchecker/ctxvars.py
nvchecker/slogconf.py
nvchecker_source/gitea.py
nvchecker_source/github.py
scripts/maintained_in_aur

Since we are targeting 3.7+, it should be safe to use them now.

Use f-string for better readability

---

nvchecker_source/github.py

Sorry for this, I overlooked it...

Fix f-string in github source

---

nvchecker_source/apt.py

It's a very noticable 20~40s to 1s improvement here.

apt: Parse Packages and cache it to improve performance

---

docs/usage.rst
nvchecker_source/git.py
tests/test_git.py

It's a thin wrapper around the cmd source, and reuses its get_cmd
function.

Add a git source

---

nvchecker_source/archpkg.py

fix the provided option for unversioned "provides"

---

tests/test_anitya.py

Almost a new version each month :)
https://github.com/shutter-project/shutter/tags

anitya: relax the test - shutter is updated often these days

---

nvchecker/tools.py

It's also useful to be able to report packages without a changed version!
Now displaying both versions in green with == instead of an arrow.

Add all option to cmp

---

docs/usage.rst
nvchecker_source/alpmfiles.py
tests/test_alpmfiles.py

Rewritten from the `archfiles` source in archlinuxcn/lilac
Related to archlinuxcn/lilac#200

Add alpmfiles source

---

docs/usage.rst
nvchecker_source/go.py
tests/test_go.py

feat: add go pkg support
