- nvchecker/source/github.py
Github now have a limit of 60 access/hour for unauthorized api access. Using access token will leverage this limit to 5000 access/hour.
Set NVCHECKER_GITHUB_TOKEN as a OAuth access token (personal access token is OK) to set access token.
> add access_token for github api, use NVCHECKER_GITHUB_TOKEN env var

- nvchecker/source/aur.py
aurname would contain some special char that needs to escape.
An example will be "libstdc++-doc" -> "libstdc%2B%2B-doc"
> escape aurname in url

- nvchecker/source/github.py
Checking a renamed github repo from github API will receive a HTTP 404 currently. However cloning the renamed repo will continue to success using the old repo url because of the graceful redirection by github. Therefore the packager will not notice the difference while nvchecker will.
This patch utilize the newly introduced [preview repository redirects](https://developer.github.com/changes/2015-04-17-preview-repository-redirects/) feature to allow renamed repo redirection when accessing from API.
This feature is currently in preview state and will be finalized in future.
An example of which will benefit from this would be the `archlinuxcn/vim-nim-git` package. It clones https://github.com/zah/nimrod.vim which will be redirected to https://github.com/zah/nim.vim
> handle github repo redirects using preview api

- nvchecker/source/aur.py
Changed to try aur4 url first, then old aur, then report error when none is found.
As discussed there:
https://github.com/archlinuxcn/repo/issues/110#issuecomment-111923122
> try aur4 url first

- nvchecker/source/github.py
The original code cause error as following.
```
[E 06-28 00:10:31.770 ioloop:612] Exception in callback functools.partial(<function wrap.
<locals>.wrapped at 0x7fe6e47b4488>, 
HTTPResponse(
_body=b'Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\n',
buffer=<_io.BytesIO object at 0x7fe6e42741c8>,
code=403,
effective_url='https://api.github.com/repos/kikyous/xfdown/commits?sha=beta',
error=HTTPError('HTTP 403: Forbidden',),
headers={'Content-Type': 'text/html', 'Connection': 'close', 'Cache-Control': 'no-cache'},
reason='Forbidden',
request=<tornado.httpclient.HTTPRequest object at 0x7fe6e47ce898>, …
```
> fixed no user-agent error for github.py

- README.rst
- nvchecker/source/gitcafe.py
gitcafe没有API, 所以就直接扒网页了。
有关授权token部分的不太清楚，不怎么用gitcafe。
> simple gitcafe.com support

- nvchecker/source/archpkg.py
- tests/test_archpkg.py
Fixes:
- `logger` was used but not defined
- `pkgrel` was not fetched, `strip_release` does nothing and the default result is missing `pkgrel`.
Enhancement:
- Use `name` as fallback to conf["archpkg"]
> Fix archpkg and add tests

- README.rst
- nvchecker/get_version.py
- nvchecker/source/gitlab.py
- tests/test_gitlab.py
Tests are currently skipped as gitlab doesn't allow anonymous API access. Specify a private token with `NVCHECKER_GITLAB_TOKEN_GITLAB_COM` env var will enable it. Please update .travis.yml for this after merging, thanks!
> Add GitLab support

- .travis.yml
- README.rst
- nvchecker/source/bitbucket.py
- nvchecker/source/github.py
- nvchecker/source/gitlab.py
- tests/test_bitbucket.py
- tests/test_github.py
- tests/test_gitlab.py
Ignore certain tags while sorting. This option must be used together with
use_max_tag. This can be useful to avoid some known badly versioned tags,
so the newer tags won't be "overriden" by the old broken ones.
> Add ignored_tags support

- README.rst
- nvchecker/source/github.py
- nvchecker/source/simple_json.py
works for me with following .ini-file (obfuscated a bit)
```
$ cat config.ini
[__config__]
oldver = old_ver.txt
newver = new_ver.txt
[Memcached]
cpan =  Cache-Memcached
proxy = proxy.example.com:3128
[nvchecker]
github = lilydjwg/nvchecker
proxy = proxy.example.com:3128
```
> Use proxy settings if set for github and cpan repos

- nvchecker/source/cpan.py
All docs in metacpan.org currently point to this new API endpoint. The
old API endpoint returns wrong data for e.g. TermReadKey (latest 2.37 vs
API 2.14), and the new API endpoint doesn't have this issue.
> CPAN: Use metacpan fastapi

- .travis.yml
`ptr` is considered deprecated and will be removed in a future version.
> Use new pytest-runner command

- nvchecker/tools.py
`nvtake foo` was giving the following error:
```
Traceback (most recent call last):
File "/usr/bin/nvtake", line 11, in <module>
load_entry_point('nvchecker==0.5', 'console_scripts', 'nvtake')()
File "/usr/lib/python3.6/site-packages/nvchecker/tools.py", line 34, in take
oldvers[name] = newvers[name]
KeyError: 'foo'
```
This is unclear and too verbose. With the change it is now:
```
[C 08-05 02:51:46.767 tools:38] foo doesn't exist in 'newver' set.
```
> Improve error message for non-exist nvtake targets

- README.rst
- nvchecker/get_version.py
- tests/test_substitute.py
Example use cases are in tests. Real usages can be found at https://github.com/yan12125/aur/blob/master/nvchecker.ini
This PR also fixes a possible bug from ac6616afd6016ed5e47ba1aaab62993471ed66fa. I'm not sure what's the scenario so I didn't add a test for that.
> Add support for substitutions of version strings

- README.rst
- nvchecker/get_version.py
- nvchecker/source/android_sdk.py
- tests/test_android.py
There are no official documents for Android SDK package manifests (repository2-1.xml and addon2-1.xml). The parsing logic is based on my observations with the help of [codes for the official ```sdkmanager``` client](https://android.googlesource.com/platform/tools/base/+/studio-master-dev).
> Support android sdk packages

- README.rst
- nvchecker/core.py
- nvchecker/source/regex.py
- tests/conftest.py
- tests/test_regex.py
- tests/test_ubuntupkg.py
I searched on the [Android NDK downloads page](https://developer.android.com/ndk/downloads/index.html) to see if there's a new version for the package `android-ndk-beta`. When the stable release (e.g., r18) is out, beta versions (e.g., r18 beta 2) are removed from the page. In this case I'd like to simply ignore no-result warnings.
> Add missing ok

- nvchecker/source/pypi.py
In my experiments, pycurl.error issues [1][2] do not appear if no 30x redirection involved.
Tested with https://github.com/tornadoweb/tornado/files/2624772/nv.log
[1] https://github.com/tornadoweb/tornado/issues/2542
[2] https://github.com/curl/curl/issues/3324
> Workaround some pycurl.error issues

- nvchecker/source/github.py
- tests/conftest.py
- tests/test_regex.py
I got "No tag found in upstream repository" errors in packages using `use_max_tag`. I was curious why it's not caught by tests, and found out that logger.warn and logger.error in tests will not trigger an error.
This pull request is incomplete as some tests are still red.
> Improve tests

- nvchecker/core.py
- nvchecker/source/regex.py
- nvchecker/tools.py
- tests/conftest.py
logging.warn is deprecated [1].
Warnings are hidden unless PYTHONWARNINGS is specified. For example:
```
$ PYTHONWARNINGS=all nvchecker foo.ini
/usr/lib/python3.7/site-packages/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
class HTTPHeaders(collections.MutableMapping):
/usr/lib/python3.7/site-packages/nvchecker/slogconf.py:49: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
msg, exc_info = exc_info, extra=std_event,
[W 03-24 00:01:02.503 core:192] foo: no-result
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='foo.ini' mode='r' encoding='UTF-8'>
```
The content of foo.ini is
```
[foo]
url = https://example.com/
regex = foo …
```
> Get rid of warnings from logging.warn

- tests/test_ubuntupkg.py
ubuntupkg tests require network
> tests: add needs_net marker to ubuntupkg tests

- tests/test_gitlab.py
- tests/test_gitlab_local.py
The repo https://gitlab.com/gitlab-org/gitlab-test gets a new tag
v1.1.1, which is for testing a new GitLab feature [1][2].
[1] https://gitlab.com/gitlab-org/gitlab/merge_requests/17773
[2] https://gitlab.com/gitlab-org/gitlab-test/merge_requests/40
> Fix gitlab tests

- nvchecker/tools.py
This is useful when the new version is somehow broken and you currently
can only update the software to a version in between. It's also useful
when you ran nvtake by accident and want to reset it back to the correct
old version.
> Allow nvtake to update to a specific version

- docs/usage.rst
- nvchecker_source/apt.py
- tests/test_apt.py
This source follows the same flow apt itself uses to check for a
package's version, so it can be used to check for any APT repository
(not necessarily Debian or Ubuntu).
> Add an APT source

- nvchecker/tools.py
The arrow is shown as backwards if the new version is older than the old
version. Also added a switch --newer to hide those with an older new
version.
> Add --sort and --newer to nvcmp

- nvchecker_source/npm.py
Ref:
https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md
For `npm` it's a 10.8MiB to 1.2MiB difference.
> npm: Request abbreviated metadata to reduce download size

- nvchecker_source/npm.py
The result is still large even after specifying
"Accept: application/vnd.npm.install-v1+json". Since the content we need
are always at the beginning of the response, let's make it more violent.
> npm: Fetch only first 1KB

- nvchecker/core.py
- tests/test_substitute.py
It's useful to have a partial match pattern to be replaced by an empty
string, like stripping a suffix. Let's allow it as "not to_pattern" will
reject this.
> Allow empty to_pattern

- docs/usage.rst
- nvchecker/api.py
- nvchecker/httpclient/__init__.py
- nvchecker/httpclient/aiohttp_httpclient.py
- nvchecker/httpclient/base.py
- nvchecker/httpclient/httpx_httpclient.py
- nvchecker/httpclient/tornado_httpclient.py
- nvchecker_source/android_sdk.py
- nvchecker_source/container.py
- tests/test_android_sdk.py
- tests/test_container.py
Closes #59
<del>Uploaded as a draft to see if CI passes</del>
<del>This PR introduces a new dependency for decoding one of OAuth2 header. If you don't want an additional dependency, please tell me and I will try to implement the decoding. (should be less than 100 lines, hopefully)</del> Copied needed parts from Werkzeug
Tested images:
* docker.io/library/python
* docker.io/library/archlinux (for testing caching of auth info)
* registry.gitlab.com/yan12125/yan12125.gitlab.io/website
* quay.io/prometheus/node-exporter
* gcr.io/google.com/cloudsdktool/cloud-sdk
* ghcr.io/br3ndonland/inboard
> Add container source plugin

- docs/usage.rst
- nvchecker_source/repology.py
- tests/test_repology.py
Without this, querying latest Fedora packages is impossible because they
reside in `updates` subrepo but old `release` versions are returned.
Same thing for openSUSE.
Example config to query Fedora 32 latest packages in updates subrepo:
```
[somepackage]
source = "repology"
repo = "fedora_32"
subrepo = "updates"
```
> repology: add support for subrepo

- nvchecker/__main__.py
This is useful for debugging purpose, when your nvchecker.toml is very
large.
> Add a command line option to run nvchecker only on a specific entry

- docs/myrst2man.py
Currently the date in the man page changes with the host time. Make it reuse the package build time.
A previous failure log: https://reproducible.archlinux.org/api/v0/builds/21343/diffoscope
> Make the generated man page reproducible

- tests/test_httpheader.py
The httpheader test requires network
> tests: add needs_net marker to httpheader test

- tests/test_anitya.py
- tests/test_pacman.py
For example, on reproducible.archlinux.org, apparently pacman databases
are not synced before building synced before building packages, and thus
packages cannot be found. From https://reproducible.archlinux.org/api/v0/builds/110565/log,
```
=================================== FAILURES ===================================
_________________________________ test_pacman __________________________________
get_version = <function get_version.<locals>.__call__ at 0x7f2fa5ed1310>
async def test_pacman(get_version):
>       assert await get_version("ipw2100-fw", {
"source": "pacman",
}) == "1.3-10"
tests/test_pacman.py:11:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/conftest.py:46: in __call__
newvers = await run(entries)
tests/conftest.py:40: in run
return …
```
> Fix test_pacman in some scenarios

- docs/usage.rst
In general, I think docs are missing a quickstart section that would cover 80% of use cases and would help people actually *not* read the docs :laughing: 
---
From 
> Specify an ini config file containing key (token) information. This file should contain a `keys` table, mapping key names to key values.
and just an example I'd surely would've picked up the latter, it's all I need to get started.
---
I had to guess `ini` here in the docs was an inaccuracy and experimented with `nvcchecker` / `nvcmp` to find keyfile to please the tool. Then I also saw encrypted `keyfile.toml.enc` in the repo :smile:
> Docs: add sample keyfile.toml

- nvchecker_source/regex.py
- tests/test_regex.py
This is a regression since 2019 [1].
Before that commit, `max()` raises `ValuError` if `re.findall` returns an
empty list. After that commit, regex fails silently if nothing is found.
[1] https://github.com/lilydjwg/nvchecker/commit/789731729472824e79e519c033a432a35cf402b2#diff-fd40f1295f9ddece86df8d2c385ddb02bd4e2a10cd20bd9a95306d3d35a9b601
Noticed this as https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/android-ndk is not automatically updated and no errors are reported.
> regex: make sure regex fails if nothing is found

- docs/usage.rst
- nvchecker/httpclient/aiohttp_httpclient.py
- nvchecker/httpclient/base.py
- nvchecker/httpclient/httpx_httpclient.py
- nvchecker/httpclient/tornado_httpclient.py
- nvchecker_source/htmlparser.py
- nvchecker_source/regex.py
- tests/test_regex.py
Example:
source = "regex"
regex = "spcm_linux_libs_v[0-9a-zA-Z]*"
url = "https://spectrum-instrumentation.com/spcm_downloads_downloads_ajax"
post_data = "series%5B%5D=273&families%5B%5D=475"
> Support HTTP POST request in the htmlparser and regex source

- docs/usage.rst
- nvchecker_source/bitbucket.py
- tests/test_bitbucket.py
Make better use of the bitbucket API to sort tags:
* use `q="my_query"` to narrow down the results. This does not support fancy regex queries, just `contains` and comparisons.
* use `sort=field` to sort the results by the given field.
* use `fields=values.name,next` to only return relevant data.
> Bitbucket: Add support for queries and sorting

- docs/usage.rst
- nvchecker_source/cran.py
- tests/test_cran.py
Add CRAN support using per-package [DESCRIPTION](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file) files unlike the previous pr (#184) that downloaded the entire database.
> Add CRAN support

- .github/workflows/tests.yaml
- docs/usage.rst
- nvchecker_source/android_sdk.py
- tests/test_android_sdk.py
* Returns all matched versions to support list options
* Don't hard-code the host OS
* Document the default of `channel`
---
I'm lazy so I put different changes in a single commit. Please tell me if you want separate commits :D
> android-sdk improvements

- docs/usage.rst
- nvchecker_source/alpm.py
it's the case where the exact repository of a package is unknown (e.g. `gcc` in either `testing` or `core`)
I'm not familiar with those packaging steps, feel free to suggest any better ideas.
> alpm source: support checking packages from multiple repos

- docs/usage.rst
- tests/test_archpkg.py
- tests/test_openvsx.py
- tests/test_pacman.py
- tests/test_vsmarketplace.py
Noticed them when I'm checking if my Python packages can be rebuilt. This is for preparing upcoming 3.11 rebuilds.
> Several minor fixes for docs and tests

- .github/workflows/mypy.yaml
- .github/workflows/tests.yaml
- README.rst
- docs/requirements.txt
- docs/usage.rst
- mypy.ini
- nvchecker/core.py
- setup.cfg
This ports to [platformdirs](https://pypi.org/project/platformdirs/), which seems to be the maintained version of `appdirs` these days. It should be backwards compatible in most cases.
The port is pretty straightforward, so just need to decide if the dependency change is worth it!
> Port from deprecated appdirs to platformdirs

- tests/test_alpm.py
Arch chroots with recent devtools has options=(debug) by default, and thus test_alpm fails:
```
_________________________ ERROR at setup of test_alpm __________________________
module = <module 'tests.test_alpm' from '/build/nvchecker/src/nvchecker/tests/test_alpm.py'>
def setup_module(module):
global temp_dir, db_path
temp_dir = tempfile.TemporaryDirectory()
temp_path = pathlib.Path(temp_dir.name)
pkg_path = temp_path / 'test-pkg'
pkg_path.mkdir()
with (pkg_path / 'PKGBUILD').open('w') as f:
f.write(
'pkgname=test-pkg\n'
'pkgver=1.2.3\n'
'pkgrel=4\n'
'arch=(any)\n'
'provides=("test-provides=5.6-7" "test-provides-unversioned")\n'
)
subprocess.check_call(['makepkg', '--nosign'], cwd=pkg_path)
pkg_file = subprocess.check_output(['makepkg', '--packagelist'], cwd=pkg_path, text=True).strip() …
```
> Fix test_alpm in Arch chroots

- nvchecker_source/httpheader.py
- nvchecker_source/regex.py
- tests/test_cran.py
Python 3.11 deprecated `sre_constants` and mostly imports from `re` now:
https://github.com/python/cpython/blob/3.11/Lib/sre_constants.py
This ports to `re.error` instead, which should be equivalent.
> Remove usage of deprecared sre_constants

- README.rst
- docs/usage.rst
- nvchecker/core.py
- nvchecker/util.py
- setup.cfg
- tests/conftest.py
Fallback to tomli for compatibility with older Python.
> Use tomllib on Python 3.11+

- tests/test_android_sdk.py
- tests/test_cran.py
See https://archriscv.felixc.at/.status/log.htm?url=logs/nvchecker/nvchecker-2.12-1.log.
> tests: bump android-sdk-cmake and xml2 version

- docs/usage.rst
- nvchecker_source/github.py
- tests/test_github.py
This PR adds the ability to return prereleases for the use_latest_release github option.
> github: implement option to include prereleases

- docs/usage.rst
- nvchecker/core.py
- nvchecker/util.py
- nvchecker_source/anitya.py
- nvchecker_source/apt.py
- nvchecker_source/archpkg.py
- nvchecker_source/bitbucket.py
- nvchecker_source/cpan.py
- nvchecker_source/cran.py
- nvchecker_source/cratesio.py
- nvchecker_source/debianpkg.py
- nvchecker_source/gems.py
- nvchecker_source/gitea.py
- nvchecker_source/github.py
- nvchecker_source/gitlab.py
- nvchecker_source/hackage.py
- nvchecker_source/npm.py
- nvchecker_source/openvsx.py
- nvchecker_source/packagist.py
- nvchecker_source/pagure.py
- nvchecker_source/repology.py
- nvchecker_source/sparkle.py
- nvchecker_source/ubuntupkg.py
- nvchecker_source/vsmarketplace.py
- tests/test_pacman.py
Based on #238, this PR adds URL result support to other sources.
Not implemented for the following sources:
- `android_sdk` - no URLs representing individual packages are available
- `container` - no universal URL schema is available, supporting docker.io would require an extra request for each tag in the list
- `alpm`, `alpmfiles`, `cmd`, `combiner`, `git`, `htmlparser`, `httpheader`, `manual`, `none`, `pacman`, `regex` - not applicable
> Implement URL result support for other sources

- nvchecker/core.py
Instead of using the passed filename as the rename target, use Path.resolve for resolving any symlinks.
This allows to use symlinks for the nvchecker database files that point somewhere else. Before this commit nvchecker simply replaced the symlink with an actual file, now we resolve the targets first and only replace the actual file that is pointed to.
> feat(core): resolve symlinks on file write

- nvchecker/tools.py
This will make `nvtake` preserve symlinks of the "old" configfile
> feat(tools): handle symlinks correctly for take command

- tests/test_cran.py
- tests/test_cratesio.py
crateios and cran released new version:
- [example](https://crates.io/crates/example)
- [xml2](https://cran.r-project.org/web/packages/xml2/index.html)
> tests: bump example and xml2 version

- nvchecker_source/container.py
- tests/test_container.py
Fix #245
For multi-arch images, registry will return Manifest List instead of Image Manifest: https://distribution.github.io/distribution/spec/manifest-v2-2/#manifest-list.
In this case, we should choose one manifest and then send another request to get its detail.
Unfortunately, it's quite hard to find the manifest matching with current CPU architecture and system (docker and Python use different enum values for architecture, for example docker uses amd64 while Python uses x86_64).
Simply choosing the first manifest should probably work for most cases.
> Fix container test for multi-arch images

- docs/usage.rst
- nvchecker/util.py
- nvchecker_source/gitea.py
- nvchecker_source/github.py
- nvchecker_source/gitlab.py
~~due to the removal of the prefix key in the token configuration, this is a breaking change.~~
closes #251
---
I tested and confirmed that I could use my netrc file (withou using the keyfile) to access the relevant gitlab token and it detected correctly the version update.
> feat: add netrc support

- docs/usage.rst
- nvchecker/core.py
- nvchecker/util.py
- nvchecker_source/git.py
- nvchecker_source/gitea.py
- nvchecker_source/github.py
- nvchecker_source/gitlab.py
- feat: add netrc support
- feat: add configurable host to github
- docs: document changes don't mention the old keys
- ↑ #252 
----
- feat: add richer results
- feat: implement more metadata for git{,hub,lab}
On top of #252, this implements expanded metadata on rich results motivated by #253.
The latter will be rebased in case this gets merged and that would allow for more
clarity on how to maybe expand the api with a suitable extension point so that
similar use cases like #253 can be implemented cleanly out of tree.
> feat: augment rich results

- docs/usage.rst
- nvchecker_source/mercurial.py
- tests/test_mercurial.py
This uses the json api of mercurial repositories. Verified to work on
the following hosting sites:
www.mercurial-scm.org/repo
hg.code.sf.net
hg.nginx.org
hg.mozilla.org
> Add a mercurial source

- nvchecker/__main__.py
- nvchecker/core.py
discussion in https://github.com/lilydjwg/nvchecker/pull/253#discussion_r1517672536
> feat: log up-to-date when single entry

- .github/workflows/tests.yaml
- docs/usage.rst
- mypy.ini
- nvchecker_source/jq.py
- setup.cfg
- tests/test_jq.py
Add a new JSON parser source which uses https://github.com/mwilliamson/jq.py ([jq](https://pypi.org/project/jq/) on PyPI, [python-jq](https://archlinux.org/packages/extra/x86_64/python-jq/) on Arch Linux), along with some tests and docs.
Tested with following config:
```toml
[otf-noto-unicode]
source = "jq"
url = "https://api.github.com/repos/MY1L/Unicode/releases/tags/NotoUni7"
filter = ".assets.[].name"
include_regex = "NotoUnicode-\\d(\\.\\d+)?\\.otf"
from_pattern = "NotoUnicode-(.*)\\.otf"
to_pattern = "\\1"
```
It shoud output
```
[I 03-31 15:44:37.623 core:408] otf-noto-unicode: updated to 7.3
```
> feat: add jq source

- tests/test_jq.py
Otherwise, it fails because Python can't find the `jq` exception.
```
==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_jq.py _______________________
tests/test_jq.py:8: in <module>
import jq
E   ModuleNotFoundError: No module named 'jq'
During handling of the above exception, another exception occurred:
tests/test_jq.py:9: in <module>
except jq:
E   NameError: name 'jq' is not defined
```
> fix: correct try/except statement

- docs/usage.rst
- nvchecker_source/pypi.py
- tests/test_pypi.py
- tests/test_ubuntupkg.py
From time to time, I need to ignore broken versions on PyPI. `ignored` or `exclude_regex` is part of list options, hence the patch.
In the new test, I use `include_regex`, which should make the test more resilient to future changes.
While I'm at it, I also cherry-picked a CI fix from the test-ci branch.
> pypi: support list options

- nvchecker_source/launchpad.py
- tests/test_launchpad.py
Add Launchpad a source for nvchecker.
This plugin only takes a single parameter:
- `launchpad`, the name of the package on Launchpad
The plugin returns however many releases are returned by the API, which appear to be returned in reverse chronological order, though this is not documented. See: https://launchpad.net/+apidoc/1.0.html#project
> Add launchpad source

- docs/usage.rst
- nvchecker_source/anitya.py
- tests/test_anitya.py
When using anitya, we need to go to https://release-monitoring.org/ and find out which distribution are linking to the project. So why don't we just use the ID.
https://release-monitoring.org/static/docs/api.html#get--api-project-(int-project_id)
> anitya: support to use anitya ID

- docs/usage.rst
- nvchecker_source/cratesio.py
- tests/test_android_sdk.py
- tests/test_archpkg.py
- tests/test_cratesio.py
- tests/test_launchpad.py
- tests/test_pypi.py
This adds a `use_pre_release` option and adds support for list option for crates.io, similar to PyPI.
> crates.io: skip pre-releases, list option

- docs/usage.rst
- nvchecker_source/rpmrepo.py
- setup.cfg
- tests/test_rpmrepo.py
> rpmrepo: new RPM repo source

- docs/usage.rst
- nvchecker_source/opam.py
- tests/test_opam.py
This PR adds a new opam source for retrieving package versions from [opam repositories](https://opam.ocaml.org/doc/Manual.html#Repositories), used in the [OCaml ecosystem](https://ocaml.org/).
Example config and output:
```toml
[omigrate]
source = "opam"
pkg = "omigrate"
```
```
[I 12-15 00:44:44.786 core:416] omigrate: updated to 0.3.2 url=https://opam.ocaml.org/packages/omigrate/omigrate.0.3.2
```
Using other repositories than the official one is also supported (but without URLs, as there is no universal URL structure):
```toml
[coq-abp]
source = "opam"
pkg = "coq-abp"
repo = "https://coq.inria.fr/opam/released"
```
```
[I 12-15 00:46:26.971 core:416] coq-abp: updated to 8.10.0
```
> feat: add opam source

- docs/usage.rst
- nvchecker/core.py
- nvchecker/slogconf.py
I'd like to track package updates using the tags then refer to the updates by their commit hash (as recommended by https://wiki.archlinux.org/title/Arch_package_guidelines#Package_sources, bullet #3).
Confirmed this works with `use_latest_tags=true` (revision is null) as well as `use_max_tag=true`.
> feat: include revision in logging output

- docs/usage.rst
- nvchecker_source/pypi.py
- setup.cfg
- tests/test_pypi.py
PyPI has a feature that allows a project maintainer to yank a release. crates.io has the same feature and the source already implements that:
https://github.com/lilydjwg/nvchecker/blob/4364759b295cf2b91402fe3270fc03338e276cb0/nvchecker_source/cratesio.py#L24-L25
This PR adds the same feature to the PyPI source.
> Exclude yanked PyPI releases

- docs/usage.rst
- nvchecker_source/github.py
- scripts/nvchecker-ini2toml
- tests/test_github.py
This follows the logic for use_max_tag but only includes the tags that are part of a github release. The returned version follows include_prerelease and use_release_name just like use_latest_release.
This allows waiting for release artifacts to be created after the tag is created on the repo. I needed this for `electron*-bin` since there could be a delay (at least a day sometimes it seems) between tag creation and artifacts upload.
> Implement use_max_release for github

- docs/usage.rst
- nvchecker_source/maven.py
- tests/test_maven.py
This PR adds a new source called "maven" that allows to fetch for new version releases from a Maven repository. As described in the updated docs, the coordinates have to be given. The repository is optional and it assumes it's Maven Central unless told otherwise.
I think this will also complete #174.
> feat: add a source for Maven

- tests/test_android_sdk.py
- tox.ini
- add py313 to tox
- replace flaky with pytest-rerunfailures to fix  
_FlakyPlugin._make_test_flaky() got an unexpected keyword argument 'reruns'
- bump android-sdk-cmake to 4
> test: fix failures
